// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYdc7J0cwS5Wpv2f7-OVynlvK368BubWg',
    appId: '1:391024485475:web:65c3e8debc199cd317c456',
    messagingSenderId: '391024485475',
    projectId: 'daftrun',
    authDomain: 'daftrun.firebaseapp.com',
    storageBucket: 'daftrun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPdE0WzsRO5RyTVA9rqo36Mi4XW0dBqFI',
    appId: '1:391024485475:android:c3f65e047329af3117c456',
    messagingSenderId: '391024485475',
    projectId: 'daftrun',
    storageBucket: 'daftrun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZrjDMBKbm7brS-7MUvSOQFfsd0V7K-TE',
    appId: '1:391024485475:ios:92580dd651b2582017c456',
    messagingSenderId: '391024485475',
    projectId: 'daftrun',
    storageBucket: 'daftrun.appspot.com',
    iosBundleId: 'com.example.daftrun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZrjDMBKbm7brS-7MUvSOQFfsd0V7K-TE',
    appId: '1:391024485475:ios:298e6ea45dc9585b17c456',
    messagingSenderId: '391024485475',
    projectId: 'daftrun',
    storageBucket: 'daftrun.appspot.com',
    iosBundleId: 'com.example.daftrun.RunnerTests',
  );
}
